refactor(common): rename package folders

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -2,4 +2,12 @@
 
 npm run pretty
 
-npm run lint || exit $?
+npm run build
+
+if [ $? -ne 0 ]; then
+    echo "Build failed, exiting."
+    exit 1
+fi
+
+npm run lint
+exit $?
